################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
Components/simpliciti/network_applications/nwk_freq.obj: ../Components/simpliciti/network_applications/nwk_freq.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/bin/cl430" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/smpl_nwk_config.dat" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/End Device/smpl_config.dat"  -vmsp -O0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/include" --include_path="/Applications/ti/ccsv6/ccs_base/msp430/include" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/nwk" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/network_applications" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/mrfi" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/drivers" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/boards/EZ430RF" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp" -g --define=MRFI_CC2500 --define=__MSP430F2274__ --silicon_errata=CPU19 --abi=eabi --printf_support=full --preproc_with_compile --preproc_dependency="Components/simpliciti/network_applications/nwk_freq.d" --obj_directory="Components/simpliciti/network_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/network_applications/nwk_ioctl.obj: ../Components/simpliciti/network_applications/nwk_ioctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/bin/cl430" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/smpl_nwk_config.dat" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/End Device/smpl_config.dat"  -vmsp -O0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/include" --include_path="/Applications/ti/ccsv6/ccs_base/msp430/include" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/nwk" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/network_applications" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/mrfi" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/drivers" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/boards/EZ430RF" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp" -g --define=MRFI_CC2500 --define=__MSP430F2274__ --silicon_errata=CPU19 --abi=eabi --printf_support=full --preproc_with_compile --preproc_dependency="Components/simpliciti/network_applications/nwk_ioctl.d" --obj_directory="Components/simpliciti/network_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/network_applications/nwk_join.obj: ../Components/simpliciti/network_applications/nwk_join.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/bin/cl430" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/smpl_nwk_config.dat" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/End Device/smpl_config.dat"  -vmsp -O0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/include" --include_path="/Applications/ti/ccsv6/ccs_base/msp430/include" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/nwk" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/network_applications" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/mrfi" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/drivers" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/boards/EZ430RF" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp" -g --define=MRFI_CC2500 --define=__MSP430F2274__ --silicon_errata=CPU19 --abi=eabi --printf_support=full --preproc_with_compile --preproc_dependency="Components/simpliciti/network_applications/nwk_join.d" --obj_directory="Components/simpliciti/network_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/network_applications/nwk_link.obj: ../Components/simpliciti/network_applications/nwk_link.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/bin/cl430" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/smpl_nwk_config.dat" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/End Device/smpl_config.dat"  -vmsp -O0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/include" --include_path="/Applications/ti/ccsv6/ccs_base/msp430/include" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/nwk" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/network_applications" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/mrfi" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/drivers" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/boards/EZ430RF" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp" -g --define=MRFI_CC2500 --define=__MSP430F2274__ --silicon_errata=CPU19 --abi=eabi --printf_support=full --preproc_with_compile --preproc_dependency="Components/simpliciti/network_applications/nwk_link.d" --obj_directory="Components/simpliciti/network_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/network_applications/nwk_mgmt.obj: ../Components/simpliciti/network_applications/nwk_mgmt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/bin/cl430" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/smpl_nwk_config.dat" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/End Device/smpl_config.dat"  -vmsp -O0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/include" --include_path="/Applications/ti/ccsv6/ccs_base/msp430/include" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/nwk" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/network_applications" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/mrfi" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/drivers" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/boards/EZ430RF" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp" -g --define=MRFI_CC2500 --define=__MSP430F2274__ --silicon_errata=CPU19 --abi=eabi --printf_support=full --preproc_with_compile --preproc_dependency="Components/simpliciti/network_applications/nwk_mgmt.d" --obj_directory="Components/simpliciti/network_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/network_applications/nwk_ping.obj: ../Components/simpliciti/network_applications/nwk_ping.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/bin/cl430" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/smpl_nwk_config.dat" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/End Device/smpl_config.dat"  -vmsp -O0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/include" --include_path="/Applications/ti/ccsv6/ccs_base/msp430/include" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/nwk" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/network_applications" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/mrfi" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/drivers" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/boards/EZ430RF" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp" -g --define=MRFI_CC2500 --define=__MSP430F2274__ --silicon_errata=CPU19 --abi=eabi --printf_support=full --preproc_with_compile --preproc_dependency="Components/simpliciti/network_applications/nwk_ping.d" --obj_directory="Components/simpliciti/network_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/network_applications/nwk_security.obj: ../Components/simpliciti/network_applications/nwk_security.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/bin/cl430" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/smpl_nwk_config.dat" --cmd_file="/Users/andys-j/Documents/CCS_projects/Demo-2016/Peer Applications/Configuration/End Device/smpl_config.dat"  -vmsp -O0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv6/tools/compiler/ti-cgt-msp430_15.12.1.LTS/include" --include_path="/Applications/ti/ccsv6/ccs_base/msp430/include" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/nwk" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/simpliciti/network_applications" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/mrfi" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/drivers" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp/boards/EZ430RF" --include_path="/Users/andys-j/Documents/CCS_projects/Demo-2016/Components/bsp" -g --define=MRFI_CC2500 --define=__MSP430F2274__ --silicon_errata=CPU19 --abi=eabi --printf_support=full --preproc_with_compile --preproc_dependency="Components/simpliciti/network_applications/nwk_security.d" --obj_directory="Components/simpliciti/network_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


